### ISSUE TITLE
Output landmark images

### ISSUE THREAD

**Issue by zinuo666** [sowwnn/KFusion-Dual-Domain-for-Speech-to-Landmarks#5]
Hello, where is the program code to output landmark images? I am looking forward to your answer thanks!

**Comment by sowwnn** [comment]
I will prepair inference code soon, But you can try it yourself. The output of model is tensor sequence of landmark not a landmark image. You can easily plot them into landmark images using matplotlib

**Comment by sowwnn** [comment]
I update the inference file, you can check and try it following the Readme file.

**Comment by zinuo666** [comment]
> I update the inference file, you can check and try it following the Readme file.
Okay. Thank you.
