### ISSUE TITLE
 No such file or directory: 'dataset/M030/infer_M030.json'

### ISSUE THREAD

**Issue by nitinmukesh** [sowwnn/KFusion-Dual-Domain-for-Speech-to-Landmarks#6]
Followed all the steps. 

I am using MEAD sample [here](https://drive.google.com/file/d/1UO2OmsBP6FqMfjDikJsXr-1QObJfzBwQ/view?usp=sharing)

```
(venv) C:\ai\KFusion>python inference.py --config config/infer.json
============================================================
{'datalist': 'dataset/M030/infer_M030.json', 'audio_path': 'dataset/M030/audio', 'landmark_path': 'dataset/M030/landmark', 'video_path': 'dataset/M030/video', 'duration': 1, 'num_workers': 4, 'batch': 1, 'device': 'cuda', 'weights': 'weights/lightning_logs/240625*/checkpoints/epoch=199-step=28800.ckpt', 'out_dir': './output/'}
============================================================
Traceback (most recent call last):
  File "C:\ai\KFusion\inference.py", line 93, in <module>
    main(args)
  File "C:\ai\KFusion\inference.py", line 81, in main
    dataloader, datas = load_data(args)
  File "C:\ai\KFusion\inference.py", line 25, in load_data
    datas = MEAD(args['datalist'], duration=args['duration'], batch=args['batch'], audio_path=args['audio_path'], landmark_path=args['landmark_path'])
  File "C:\ai\KFusion\dataloader\dataloader.py", line 13, in __init__
    with open(data_path,"r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/M030/infer_M030.json'

```

Also what does this means?
> (If used MEAD data you need to pre-processing by utils folder)

I guess this need to be used with MEAD dataset [here](https://github.com/uniBruce/Mead)?
How to pre-process by utils folder. What is the command

**Comment by sowwnn** [comment]
If you use sample dataset, just take some item in datalist_M030.json that I provide.
About pre-process, I will update it soon.

**Comment by sowwnn** [comment]
Structure of datalist is similar to datalist.json file.
You can use the following content

`[
    {
        "video": "M030_front_surprised_level_3_014.mp4",
        "audio": "M030_surprised_level_3_014.wav",
        "landmark": "M030_front_surprised_level_3_014.npy",
        "emotion": 5,
        "name": "M030_surprised_level_3_014"
    },
    {
        "video": "M030_front_neutral_level_1_040.mp4",
        "audio": "M030_neutral_level_1_040.wav",
        "landmark": "M030_front_neutral_level_1_040.npy",
        "emotion": 7,
        "name": "M030_neutral_level_1_040"
    }
]`

**Comment by nitinmukesh** [comment]
Thank you @sowwnn 

I will try it now.
